---
title: |
  \vspace{-2cm}
  \begin{flushright}
  {\small \textit{Student ID: 7038293}}
  \end{flushright}
  Analysing Roadkill Trends in the UK: Identifying Spatial and Temporal Patterns
output: pdf_document
bibliography: roadkill.bib
csl: ieee.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

**Topics:** Data Wrangling, Advanced Visualisation, RMarkdown, Hierarchical Modelling, Spatial Visualisation, Temporal Trends

With the ever-changing climate, British wildlife face an uncertain future, with a major decline in biodiversity being found all around the United Kingdom. But another thing that could be adding to the decline in British wildlife is road-traffic-accidents; collisions with vehicles is one of the major causes of wild animal death in the UK [@raymond_temporal_2021]. For animals that are already under immense pressure due to anthropogenic and climate threats, roadkill could push some of these species to extinction.

This report aims to provide a comprehensive exploration of roadkill trends across the UK, leveraging data science techniques to address questions about its spatial, temporal and environmental dynamics, with a specific focus on mammals.

Focusing on mammals is particularly relevant due to their ecological importance and the disproportionate impact of roadkill on their populations. Many mammal species are wide ranging with large territories that are increasingly being split up by roads, making them more vulnerable to collisions. By narrowing the scope to mammals, this study aims to provide actionable insights for mitigating roadkill impacts on vulnerable mammalian species.

The four main questions I am hoping to answer are:

1.  What are the spatial and seasonal trends in mammalian roadkill numbers?

2.  Do temperature or rainfall play a role in mammalian roadkill prevalence?

3.  Where are the mammalian roadkill hotspots across the UK?

4.  Which mammalian species are most commonly recorded as roadkill?

## Objectives/Methodology

## Data

### Roadkill Data

The data I will use is from The Road Lab (formerly 'Project Splatter') [<https://www.theroadlab.co.uk/>], it is a citizen science project with 57 columns and 68,212 rows of data. The dataset includes mammals, birds, amphibians and reptiles but, as this report is only interested in mammals, all rows corresponding with other Orders are removed.

Data was collected between 01/01/2014 until 30/09/2024 but as there was only one entry and it was not the complete year, data from 2024 was removed. There were several recordings of “indet. Deer” which were removed along with any other sightings that weren’t confirmed to a species level, so in total **X** were removed.

Once all unneeded data was removed, I was left with **X** entries.

### Seasonal/Weather Data

This data will then be combined with data on the mean monthly temperature and total rainfall per month from the Met Office.

According to the met office, the seasons will be split into months. Spring = MArch, April, May, Summer = June, July, August, Autumn = September, October, November and Winter = December, January and February

### Spatial/Traffic Data

Mean monthly traffic levels will also be used when looking into roadkill hotspots as a potential explanation for these hotspots.

## Results

### Exploratory Analysis

What I want to include:

-   Overall number of reports per month

-   Reports per season

-   Multiple maps of the UK showing reports per season

-   Overall species' barchart

### Seasonal trends in roadkill

### Spatial Trends in roadkill

## Limitations

-   Larger species are more likely to be seen and reported

-   Only covers animals that die immediately and not those that get out of the road before dying

-   Citizen science always comes with limitations

-   Bias in sampling

-   However, previous studies in South Africa (REF: <https://www.frontiersin.org/journals/ecology-and-evolution/articles/10.3389/fevo.2018.00015/full>) and California have shown the identification data to be reliable (REF: <https://www.frontiersin.org/journals/ecology-and-evolution/articles/10.3389/fevo.2017.00089/full>)

## Conclusion

## Reproducibility

All code and data files used for the analysis in this report can be found in a GitHub repository here:

## References
